name: python-Levenshtein 0.12.2

defaults:
  run:
    shell: bash

on: pull_request

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.1.2

      - name: Fetch source distribution
        run: |
          curl https://files.pythonhosted.org/packages/2a/dc/97f2b63ef0fa1fd78dcb7195aca577804f6b2b51e712516cc0e902a9a201/python-Levenshtein-0.12.2.tar.gz -o python-Levenshtein-0.12.2.tar.gz
          tar -zxf python-Levenshtein-0.12.2.tar.gz
          mv python-Levenshtein-0.12.2/* .

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.7"
          CIBW_BUILD: "cp*"

      - name: Checksum Linux
        if: ${{ runner.os == 'Linux' }}
        run: sha256sum wheelhouse/*

      - name: Checksum Windows
        if: ${{ runner.os == 'Windows' }}
        run: |
          for file in $(ls wheelhouse)
          do
            certutil -hashfile wheelhouse/$file SHA256
          done

      - name: Checksum Mac
        if: ${{ runner.os == 'macOS' }}
        run: shasum -a 256 wheelhouse/*

      - uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*.whl

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: 'Release: python-Levenshtein 0.12.2-4'
          files: wheelhouse/*.whl
          tag_name: python-levenshtein-0.12.2-4
