name: uvloop 0.16.0

defaults:
  run:
    shell: bash

on: pull_request

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.1.2

      - name: Fetch source distribution
        run: |
          curl https://files.pythonhosted.org/packages/ab/d9/22bbffa8f8d7e075ccdb29e8134107adfb4710feb10039f9d357db8b589c/uvloop-0.16.0.tar.gz -o uvloop-0.16.0.tar.gz
          tar -zxf uvloop-0.16.0.tar.gz
          mv uvloop-0.16.0/* .

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.7"
          CIBW_BUILD: "cp*"

      - name: Checksum
        uses: Huy-Ngo/gha-sha@v1.1.0
        with:
          glob: 'wheelhouse/*.whl'
      - uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*.whl

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: 'Release: uvloop 0.16.0'
          files: wheelhouse/*.whl
          tag_name: uvloop-0.16.0

