name: pytest-env 0.6.2

defaults:
  run:
    shell: bash

on: pull_request

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.1.2

      - name: Fetch source distribution
        run: |
          curl https://files.pythonhosted.org/packages/f9/6e/31efb8dc1d17052c12f39262223e94038bfcc4cc7a124235630a6d50f166/pytest-env-0.6.2.tar.gz -o pytest-env-0.6.2.tar.gz
          tar -zxf pytest-env-0.6.2.tar.gz
          mv pytest-env-0.6.2/* .

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.7"
          CIBW_BUILD: "cp*"

      - name: Checksum
        uses: Huy-Ngo/gha-sha@v1.1.0
        with:
          glob: 'wheelhouse/*.whl'
      - uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*.whl

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: 'Release: pytest-env 0.6.2'
          files: wheelhouse/*.whl
          tag_name: pytest-env-0.6.2

