name: hypothesis-fspaths 0.1

defaults:
  run:
    shell: bash

on: pull_request

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.1.2

      - name: Fetch source distribution
        run: |
          curl https://files.pythonhosted.org/packages/be/00/208e4c5be58fdc92aa7bfac82e94c524150183fc8b0ec995d70d6e0db43c/hypothesis-fspaths-0.1.tar.gz
          tar -zxf hypothesis-fspaths-0.1.tar.gz
          mv hypothesis-fspaths-0.1/* .

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.7"
          CIBW_BUILD: "cp*"

      - name: Checksum Linux
        if: ${{ runner.os == 'Linux' }}
        run: sha256sum wheelhouse/*

      - name: Checksum Windows
        if: ${{ runner.os == 'Windows' }}
        run: |
          for file in $(ls wheelhouse)
          do
            certutil -hashfile wheelhouse/$file SHA256
          done

      - name: Checksum Mac
        if: ${{ runner.os == 'macOS' }}
        run: shasum -a 256 wheelhouse/*

      - uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*.whl

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: 'Release: hypothesis-fspaths 0.1'
          files: wheelhouse/*.whl
          tag_name: hypothesis-fspaths-0.1

